"""CLI integration tests for ``wd bench --public`` (ADR 0059).

Exercises the CLI surface end-to-end against the smoke corpus shipped in
``weld/bench/fixtures/public_corpus_smoke/``. The full Tier-2 5-repo
corpus is never invoked in CI.
"""

from __future__ import annotations

import io
import tempfile
import unittest
from importlib.metadata import PackageNotFoundError
from pathlib import Path
from unittest.mock import patch


from weld._version import DISTRIBUTION_NAME  # noqa: E402
from weld.cli import main as cli_main  # noqa: E402


def _installed_weld(name: str) -> str:
    """Stand-in for ``importlib.metadata.version`` on an installed weld.

    The default-report-path cases pin the version rather than reading the
    ambient one, so a checkout, a wheel and CI all assert the same name.
    Nothing else on the ``--public`` path asks ``importlib.metadata``
    anything, so answering only for weld's distribution is enough.
    """
    if name != DISTRIBUTION_NAME:
        raise PackageNotFoundError(name)
    return "9.9.9"


_SMOKE_DIR = (
    Path(__file__).resolve().parent.parent.parent
    / "bench"
    / "fixtures"
    / "public_corpus_smoke"
)
_SMOKE_MANIFEST = _SMOKE_DIR / "smoke_corpus.yaml"


class PublicBenchCliTest(unittest.TestCase):
    def test_runs_smoke_corpus_and_writes_report(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "report.md"
            rc = cli_main(
                [
                    "bench",
                    "--public",
                    "--corpus",
                    str(_SMOKE_MANIFEST),
                    "--out",
                    str(out),
                ]
            )
            self.assertEqual(rc, 0)
            self.assertTrue(out.exists())
            text = out.read_text(encoding="utf-8")
            self.assertIn("# Weld public benchmark", text)
            self.assertIn("## Methodology", text)
            self.assertIn("## Caveats", text)

    def _run_with_default_out(self, root: Path) -> int:
        """Run ``--public`` with no ``--out``, so the CLI picks the path."""
        return cli_main(
            [
                "bench",
                "--public",
                "--corpus",
                str(_SMOKE_MANIFEST),
                "--root",
                str(root),
            ]
        )

    def test_default_path_names_the_weld_its_header_names(self) -> None:
        # Without --out the path is chosen before the run has produced
        # anything to read a version off, so the version is resolved a
        # second time -- which is how a report ends up named after one
        # version and headered with another. Assert the artifact against
        # its own first line.
        with tempfile.TemporaryDirectory() as tmp, patch(
            "importlib.metadata.version", _installed_weld,
        ):
            root = Path(tmp)
            self.assertEqual(self._run_with_default_out(root), 0)

            report = root / "docs" / "bench" / "PUBLIC-BENCHMARK-9.9.9.md"
            self.assertTrue(
                report.exists(),
                f"wrote {sorted((root / 'docs' / 'bench').glob('*'))}",
            )
            self.assertEqual(
                report.read_text(encoding="utf-8").splitlines()[0],
                "# Weld public benchmark (9.9.9)",
            )

    def test_default_path_ignores_the_benchmarked_repos_version(self) -> None:
        # --root is someone else's project. Its VERSION dates *that*
        # project, so it must not end up naming a report about weld.
        with tempfile.TemporaryDirectory() as tmp, patch(
            "importlib.metadata.version", _installed_weld,
        ):
            root = Path(tmp)
            (root / "VERSION").write_text("7.7.7\n", encoding="utf-8")
            self.assertEqual(self._run_with_default_out(root), 0)

            written = sorted((root / "docs" / "bench").glob("*.md"))
            self.assertEqual(
                [path.name for path in written],
                ["PUBLIC-BENCHMARK-9.9.9.md"],
            )

    def test_verify_passes_on_smoke_corpus(self) -> None:
        # First run produces the canonical report; --verify reruns and
        # asserts byte-identity.
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "report.md"
            rc = cli_main(
                [
                    "bench",
                    "--public",
                    "--corpus",
                    str(_SMOKE_MANIFEST),
                    "--out",
                    str(out),
                ]
            )
            self.assertEqual(rc, 0)
            self.assertTrue(out.exists())
            # Verify mode requires the report be present; passes when
            # the regenerated bytes match.
            rc = cli_main(
                [
                    "bench",
                    "--public",
                    "--verify",
                    "--corpus",
                    str(_SMOKE_MANIFEST),
                    "--out",
                    str(out),
                ]
            )
            self.assertEqual(rc, 0)

    def test_verify_fails_when_report_missing(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "missing.md"
            buf = io.StringIO()
            with patch("sys.stdout", buf):
                rc = cli_main(
                    [
                        "bench",
                        "--public",
                        "--verify",
                        "--corpus",
                        str(_SMOKE_MANIFEST),
                        "--out",
                        str(out),
                    ]
                )
            self.assertEqual(rc, 1)
            self.assertIn("missing", buf.getvalue().lower())

    def test_print_mode_does_not_write(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "report.md"
            buf = io.StringIO()
            with patch("sys.stdout", buf):
                rc = cli_main(
                    [
                        "bench",
                        "--public",
                        "--corpus",
                        str(_SMOKE_MANIFEST),
                        "--out",
                        str(out),
                        "--print",
                    ]
                )
            self.assertEqual(rc, 0)
            self.assertFalse(out.exists())
            self.assertIn("Weld public benchmark", buf.getvalue())

    def test_unknown_corpus_errors(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            missing = Path(tmp) / "nope.yaml"
            out = Path(tmp) / "x.md"
            buf = io.StringIO()
            with patch("sys.stdout", buf):
                rc = cli_main(
                    [
                        "bench",
                        "--public",
                        "--corpus",
                        str(missing),
                        "--out",
                        str(out),
                    ]
                )
            self.assertEqual(rc, 1)
            self.assertIn("not found", buf.getvalue().lower())


if __name__ == "__main__":
    unittest.main()
