"""CLI integration tests for ``wd bench --public`` (ADR 0059).

Exercises the CLI surface end-to-end against the smoke corpus shipped in
``weld/bench/fixtures/public_corpus_smoke/``. The full Tier-2 5-repo
corpus is never invoked in CI.
"""

from __future__ import annotations

import io
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


from weld.cli import main as cli_main  # noqa: E402

_SMOKE_DIR = (
    Path(__file__).resolve().parent.parent.parent
    / "bench"
    / "fixtures"
    / "public_corpus_smoke"
)
_SMOKE_MANIFEST = _SMOKE_DIR / "smoke_corpus.yaml"


class PublicBenchCliTest(unittest.TestCase):
    def test_runs_smoke_corpus_and_writes_report(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "report.md"
            rc = cli_main(
                [
                    "bench",
                    "--public",
                    "--corpus",
                    str(_SMOKE_MANIFEST),
                    "--out",
                    str(out),
                ]
            )
            self.assertEqual(rc, 0)
            self.assertTrue(out.exists())
            text = out.read_text(encoding="utf-8")
            self.assertIn("# Weld public benchmark", text)
            self.assertIn("## Methodology", text)
            self.assertIn("## Caveats", text)

    def test_verify_passes_on_smoke_corpus(self) -> None:
        # First run produces the canonical report; --verify reruns and
        # asserts byte-identity.
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "report.md"
            rc = cli_main(
                [
                    "bench",
                    "--public",
                    "--corpus",
                    str(_SMOKE_MANIFEST),
                    "--out",
                    str(out),
                ]
            )
            self.assertEqual(rc, 0)
            self.assertTrue(out.exists())
            # Verify mode requires the report be present; passes when
            # the regenerated bytes match.
            rc = cli_main(
                [
                    "bench",
                    "--public",
                    "--verify",
                    "--corpus",
                    str(_SMOKE_MANIFEST),
                    "--out",
                    str(out),
                ]
            )
            self.assertEqual(rc, 0)

    def test_verify_fails_when_report_missing(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "missing.md"
            buf = io.StringIO()
            with patch("sys.stdout", buf):
                rc = cli_main(
                    [
                        "bench",
                        "--public",
                        "--verify",
                        "--corpus",
                        str(_SMOKE_MANIFEST),
                        "--out",
                        str(out),
                    ]
                )
            self.assertEqual(rc, 1)
            self.assertIn("missing", buf.getvalue().lower())

    def test_print_mode_does_not_write(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "report.md"
            buf = io.StringIO()
            with patch("sys.stdout", buf):
                rc = cli_main(
                    [
                        "bench",
                        "--public",
                        "--corpus",
                        str(_SMOKE_MANIFEST),
                        "--out",
                        str(out),
                        "--print",
                    ]
                )
            self.assertEqual(rc, 0)
            self.assertFalse(out.exists())
            self.assertIn("Weld public benchmark", buf.getvalue())

    def test_unknown_corpus_errors(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            missing = Path(tmp) / "nope.yaml"
            out = Path(tmp) / "x.md"
            buf = io.StringIO()
            with patch("sys.stdout", buf):
                rc = cli_main(
                    [
                        "bench",
                        "--public",
                        "--corpus",
                        str(missing),
                        "--out",
                        str(out),
                    ]
                )
            self.assertEqual(rc, 1)
            self.assertIn("not found", buf.getvalue().lower())


if __name__ == "__main__":
    unittest.main()
