"""Tests for ``wd agents render`` and rendered-content drift audit (ADR 0026)."""

from __future__ import annotations

import io
import json
import os
import sys
import tempfile
import unittest
from contextlib import contextmanager, redirect_stderr, redirect_stdout
from pathlib import Path
from typing import Iterator

_repo_root = str(Path(__file__).resolve().parent.parent.parent)
if _repo_root not in sys.path:
    sys.path.insert(0, _repo_root)

from weld.cli import main as wd_main  # noqa: E402


@contextmanager
def _cwd(path: Path) -> Iterator[None]:
    old = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(old)


def _write(root: Path, rel_path: str, text: str) -> None:
    path = root / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _read(root: Path, rel_path: str) -> str:
    return (root / rel_path).read_text(encoding="utf-8")


def _run(argv: list[str], root: Path) -> tuple[int, str, str]:
    out = io.StringIO()
    err = io.StringIO()
    with _cwd(root), redirect_stdout(out), redirect_stderr(err):
        rc = wd_main(argv)
    return rc, out.getvalue(), err.getvalue()


def _render_workspace(root: Path) -> None:
    """Set up a workspace with a canonical agent and a declared rendered copy."""
    _write(
        root,
        ".github/agents/planner.agent.md",
        "---\n"
        "name: planner\n"
        "description: Plans implementation changes.\n"
        "---\n"
        "Body of the planner agent.\n",
    )
    _write(
        root,
        ".weld/agents.yaml",
        "agents:\n"
        "  planner:\n"
        "    canonical: .github/agents/planner.agent.md\n"
        "    renders:\n"
        "      - .claude/agents/planner.md\n",
    )


class AgentsRenderHelpTest(unittest.TestCase):
    def test_render_help_marks_command_as_preview(self) -> None:
        out = io.StringIO()
        err = io.StringIO()
        with redirect_stdout(out), redirect_stderr(err):
            try:
                wd_main(["agents", "render", "--help"])
            except SystemExit as exc:
                self.assertEqual(exc.code, 0)
        self.assertIn("[preview]", out.getvalue().lower())


class AgentsRenderDryRunTest(unittest.TestCase):
    def test_default_is_dry_run_and_does_not_write(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)
            target = root / ".claude/agents/planner.md"

            rc, stdout, stderr = _run(["agents", "render"], root)

            # Drift exists (target is missing) -> non-zero exit, but no write.
            self.assertNotEqual(rc, 0, msg=stderr)
            self.assertFalse(target.exists())
            self.assertIn(".claude/agents/planner.md", stdout)

    def test_json_dry_run_emits_plan_without_writing(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)
            target = root / ".claude/agents/planner.md"

            rc, stdout, stderr = _run(["agents", "render", "--json"], root)

            self.assertNotEqual(rc, 0, msg=stderr)
            self.assertFalse(target.exists())
            payload = json.loads(stdout)
            self.assertEqual(len(payload["pairs"]), 1)
            pair = payload["pairs"][0]
            self.assertEqual(pair["canonical"], ".github/agents/planner.agent.md")
            self.assertEqual(pair["rendered"], ".claude/agents/planner.md")
            self.assertEqual(pair["action"], "create")


class AgentsRenderWriteTest(unittest.TestCase):
    def test_write_creates_missing_target_with_provenance_header(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)
            target = root / ".claude/agents/planner.md"

            rc, _stdout, stderr = _run(["agents", "render", "--write"], root)

            self.assertEqual(rc, 0, msg=stderr)
            self.assertTrue(target.exists())
            content = _read(root, ".claude/agents/planner.md")
            self.assertIn("Generated by Weld", content)
            self.assertIn(".github/agents/planner.agent.md", content)
            # Body of canonical (sans frontmatter) is preserved.
            self.assertIn("Body of the planner agent.", content)
            # Frontmatter is stripped from rendered output.
            self.assertNotIn("description: Plans implementation changes.", content)

    def test_write_is_idempotent_when_target_already_in_sync(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)

            rc, _, _ = _run(["agents", "render", "--write"], root)
            self.assertEqual(rc, 0)
            mtime1 = (root / ".claude/agents/planner.md").stat().st_mtime_ns

            # Second invocation: nothing to do, no diff, exit 0.
            rc, _, _ = _run(["agents", "render"], root)
            self.assertEqual(rc, 0)
            mtime2 = (root / ".claude/agents/planner.md").stat().st_mtime_ns
            self.assertEqual(mtime1, mtime2)


class AgentsRenderClobberTest(unittest.TestCase):
    def test_write_refuses_to_clobber_existing_drifted_target(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)
            _write(
                root,
                ".claude/agents/planner.md",
                "hand-written content that we should not lose\n",
            )

            rc, _stdout, stderr = _run(["agents", "render", "--write"], root)

            # Refusal -> non-zero exit; original bytes preserved.
            self.assertNotEqual(rc, 0)
            self.assertIn("force", stderr.lower())
            self.assertIn(
                "hand-written content",
                _read(root, ".claude/agents/planner.md"),
            )

    def test_force_overwrites_existing_drifted_target(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)
            _write(
                root,
                ".claude/agents/planner.md",
                "hand-written content that we should overwrite\n",
            )

            rc, _, stderr = _run(["agents", "render", "--write", "--force"], root)

            self.assertEqual(rc, 0, msg=stderr)
            content = _read(root, ".claude/agents/planner.md")
            self.assertIn("Generated by Weld", content)
            self.assertIn("Body of the planner agent.", content)
            self.assertNotIn("hand-written content", content)


class AgentsRenderPathSafetyTest(unittest.TestCase):
    def test_render_refuses_to_write_outside_repo_root(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td) / "repo"
            root.mkdir()
            outside = Path(td) / "victim.md"
            _write(
                root,
                ".github/agents/planner.agent.md",
                "---\nname: planner\n---\nbody\n",
            )
            _write(
                root,
                ".weld/agents.yaml",
                "agents:\n"
                "  planner:\n"
                "    canonical: .github/agents/planner.agent.md\n"
                "    renders:\n"
                "      - ../victim.md\n",
            )

            rc, _, stderr = _run(["agents", "render", "--write"], root)

            self.assertNotEqual(rc, 0)
            self.assertFalse(outside.exists())
            self.assertIn("path_escapes_root", stderr.lower())


class AgentsRenderAuditDriftTest(unittest.TestCase):
    def test_audit_detects_byte_level_drift(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)

            # Render once so the target exists.
            self.assertEqual(_run(["agents", "render", "--write"], root)[0], 0)
            # Hand-edit the rendered copy: bytes drift, but description
            # does not change so the legacy description-level finding stays
            # silent. The new content-level finding must fire.
            target = root / ".claude/agents/planner.md"
            target.write_text(
                target.read_text(encoding="utf-8") + "extra unauthorized line\n",
                encoding="utf-8",
            )

            self.assertEqual(_run(["agents", "discover"], root)[0], 0)
            rc, stdout, stderr = _run(["agents", "audit", "--json"], root)

            self.assertEqual((rc, stderr), (0, ""))
            codes = {f["code"] for f in json.loads(stdout)["findings"]}
            self.assertIn("rendered_copy_content_drift", codes)

    def test_audit_clean_when_rendered_copy_is_in_sync(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)

            self.assertEqual(_run(["agents", "render", "--write"], root)[0], 0)
            self.assertEqual(_run(["agents", "discover"], root)[0], 0)
            rc, stdout, stderr = _run(["agents", "audit", "--json"], root)

            self.assertEqual((rc, stderr), (0, ""))
            codes = {f["code"] for f in json.loads(stdout)["findings"]}
            self.assertNotIn("rendered_copy_content_drift", codes)


class AgentsExplainCanonicalRenderedTest(unittest.TestCase):
    """ADR 0029: explain surfaces canonical/derived relationship."""

    def test_explain_on_derived_target_lists_canonical_source(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)
            self.assertEqual(_run(["agents", "render", "--write"], root)[0], 0)
            self.assertEqual(_run(["agents", "discover"], root)[0], 0)

            rc, stdout, stderr = _run(
                ["agents", "explain", ".claude/agents/planner.md"], root,
            )

            self.assertEqual((rc, stderr), (0, ""))
            self.assertIn("Canonical source:", stdout)
            self.assertIn(".github/agents/planner.agent.md", stdout)

    def test_explain_on_canonical_lists_rendered_targets(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)
            self.assertEqual(_run(["agents", "render", "--write"], root)[0], 0)
            self.assertEqual(_run(["agents", "discover"], root)[0], 0)

            rc, stdout, stderr = _run(
                ["agents", "explain", ".github/agents/planner.agent.md"], root,
            )

            self.assertEqual((rc, stderr), (0, ""))
            self.assertIn("Rendered targets:", stdout)
            self.assertIn(".claude/agents/planner.md", stdout)

    def test_explain_json_payload_carries_canonical_and_rendered_fields(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _render_workspace(root)
            self.assertEqual(_run(["agents", "render", "--write"], root)[0], 0)
            self.assertEqual(_run(["agents", "discover"], root)[0], 0)

            rc, stdout, stderr = _run(
                ["agents", "explain", ".claude/agents/planner.md", "--json"],
                root,
            )

            self.assertEqual((rc, stderr), (0, ""))
            payload = json.loads(stdout)
            self.assertIn("canonical_source", payload)
            self.assertIsNotNone(payload["canonical_source"])
            self.assertEqual(
                payload["canonical_source"]["node"]["path"],
                ".github/agents/planner.agent.md",
            )
            self.assertEqual(payload.get("rendered_targets", []), [])

            rc, stdout, _ = _run(
                ["agents", "explain", ".github/agents/planner.agent.md", "--json"],
                root,
            )
            self.assertEqual(rc, 0)
            payload = json.loads(stdout)
            self.assertIsNone(payload.get("canonical_source"))
            self.assertEqual(len(payload["rendered_targets"]), 1)
            self.assertEqual(
                payload["rendered_targets"][0]["node"]["path"],
                ".claude/agents/planner.md",
            )


if __name__ == "__main__":
    unittest.main()
