"""CLI tests for ``wd agents audit --strict``.

ADR 0029 silences ``duplicate_name`` and ``vague_description`` findings
when assets form a canonical->rendered pair. Strict mode lets operators
see WHAT is being suppressed so they can verify the canonical+rendered
relationship is intentional. ADR 0029 explicitly marks ``--strict`` as
out of scope; this test file pins the follow-up contract.
"""

from __future__ import annotations

import io
import json
import os
import sys
import tempfile
import unittest
from contextlib import contextmanager, redirect_stderr, redirect_stdout
from pathlib import Path
from typing import Iterator

_repo_root = str(Path(__file__).resolve().parent.parent.parent)
if _repo_root not in sys.path:
    sys.path.insert(0, _repo_root)

from weld.cli import main as wd_main  # noqa: E402


@contextmanager
def _cwd(path: Path) -> Iterator[None]:
    old = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(old)


def _write(root: Path, rel_path: str, text: str) -> None:
    path = root / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _run(argv: list[str], root: Path) -> tuple[int, str, str]:
    out = io.StringIO()
    err = io.StringIO()
    with _cwd(root), redirect_stdout(out), redirect_stderr(err):
        rc = wd_main(argv)
    return rc, out.getvalue(), err.getvalue()


def _canonical_rendered_workspace(root: Path) -> None:
    """Customer scratch repo: canonical Copilot agent + rendered Claude target."""
    _write(
        root,
        ".github/agents/planner.agent.md",
        "---\n"
        "name: planner\n"
        "description: Plans implementation changes.\n"
        "---\n"
        "Body of the planner agent.\n",
    )
    _write(
        root,
        ".weld/agents.yaml",
        "agents:\n"
        "  planner:\n"
        "    canonical: .github/agents/planner.agent.md\n"
        "    renders:\n"
        "      - .claude/agents/planner.md\n",
    )
    _write(
        root,
        ".claude/agents/planner.md",
        "<!-- Generated by Weld from .github/agents/planner.agent.md;"
        " do not edit by hand. -->\n"
        "<!-- Run `wd agents render` to regenerate. -->\n"
        "Body of the planner agent.\n",
    )


def _findings(root: Path, *, strict: bool) -> list[dict]:
    rc_discover, _out, _err = _run(["agents", "discover"], root)
    assert rc_discover == 0, _err
    argv = ["agents", "audit", "--json"]
    if strict:
        argv.append("--strict")
    rc, stdout, stderr = _run(argv, root)
    assert (rc, stderr) == (0, ""), stderr
    return json.loads(stdout)["findings"]


class AgentGraphAuditStrictModeTest(unittest.TestCase):
    """`wd agents audit --strict` surfaces canonical+rendered groups that
    the default mode silently suppresses. Severity is ``info`` and the
    code is suffixed with ``_suppressed`` so downstream tools can filter
    them without touching the existing finding catalog."""

    def test_strict_surfaces_suppressed_duplicate_name_pair(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _canonical_rendered_workspace(root)
            findings = _findings(root, strict=True)
            matches = [
                f for f in findings
                if f["code"] == "duplicate_name_suppressed"
                and any(n["name"] == "planner" for n in f["nodes"])
            ]
            self.assertEqual(len(matches), 1, msg=findings)
            self.assertEqual(matches[0]["severity"], "info")
            paths = {n["path"] for n in matches[0]["nodes"]}
            self.assertIn(".github/agents/planner.agent.md", paths)
            self.assertIn(".claude/agents/planner.md", paths)

    def test_strict_surfaces_suppressed_vague_description_for_rendered(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _canonical_rendered_workspace(root)
            findings = _findings(root, strict=True)
            matches = [
                f for f in findings
                if f["code"] == "vague_description_suppressed"
                and any(
                    ".claude/agents/planner.md" in n.get("path", "")
                    for n in f["nodes"]
                )
            ]
            self.assertEqual(len(matches), 1, msg=findings)
            self.assertEqual(matches[0]["severity"], "info")

    def test_default_mode_remains_silent_for_canonical_rendered_pair(
        self,
    ) -> None:
        """Pin the regression: without --strict, neither the original
        suppressed codes nor the new info-level codes should surface."""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _canonical_rendered_workspace(root)
            findings = _findings(root, strict=False)
            silenced = {
                "duplicate_name",
                "duplicate_name_suppressed",
                "vague_description_suppressed",
            }
            offending = [
                f for f in findings
                if f["code"] in silenced
                and any(n["name"] == "planner" for n in f["nodes"])
            ]
            self.assertEqual(offending, [], msg=findings)

    def test_strict_does_not_double_count_unrelated_duplicates(self) -> None:
        """Unrelated duplicates already produce a regular ``duplicate_name``
        finding; --strict must not also emit a ``_suppressed`` variant for
        them. Suppression info is only for genuinely-suppressed groups."""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _write(
                root,
                ".github/agents/planner.agent.md",
                "---\nname: planner\ndescription: Plans implementation.\n---\n",
            )
            _write(
                root,
                ".claude/agents/planner.md",
                "---\nname: planner\ndescription: Drafts implementation.\n---\n",
            )
            findings = _findings(root, strict=True)
            suppressed = [
                f for f in findings
                if f["code"] == "duplicate_name_suppressed"
                and any(n["name"] == "planner" for n in f["nodes"])
            ]
            self.assertEqual(suppressed, [], msg=findings)
            regular = [
                f for f in findings
                if f["code"] == "duplicate_name"
                and any(n["name"] == "planner" for n in f["nodes"])
            ]
            self.assertEqual(len(regular), 1, msg=findings)


if __name__ == "__main__":
    unittest.main()
