"""Authority and drift tests for static Agent Graphs."""

from __future__ import annotations

import io
import json
import os
import sys
import tempfile
import unittest
from contextlib import contextmanager, redirect_stderr, redirect_stdout
from pathlib import Path
from typing import Iterator

_repo_root = str(Path(__file__).resolve().parent.parent.parent)
if _repo_root not in sys.path:
    sys.path.insert(0, _repo_root)

from weld.cli import main as wd_main  # noqa: E402


@contextmanager
def _cwd(path: Path) -> Iterator[None]:
    old = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(old)


def _write(root: Path, rel_path: str, text: str = "content\n") -> None:
    path = root / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _run(argv: list[str], root: Path) -> tuple[int, str, str]:
    out = io.StringIO()
    err = io.StringIO()
    with _cwd(root), redirect_stdout(out), redirect_stderr(err):
        rc = wd_main(argv)
    return rc, out.getvalue(), err.getvalue()


class AgentGraphAuthorityTest(unittest.TestCase):
    def test_sidecar_authority_prioritizes_canonical_impact(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _authority_workspace(root)

            self.assertEqual(_run(["agents", "discover"], root)[0], 0)
            rc, stdout, stderr = _run(["agents", "impact", "planner", "--json"], root)

            self.assertEqual((rc, stderr), (0, ""))
            payload = json.loads(stdout)
            self.assertEqual(payload["asset"]["path"], ".github/agents/planner.agent.md")
            self.assertEqual(payload["asset"]["status"], "canonical")
            self.assertEqual(
                [asset["path"] for asset in payload["canonical_assets"]],
                [".github/agents/planner.agent.md"],
            )
            self.assertIn(
                ".claude/agents/planner.md",
                {asset["path"] for asset in payload["affected_nodes"]},
            )

            rc, stdout, stderr = _run(
                ["agents", "impact", ".claude/agents/planner.md", "--json"],
                root,
            )

            self.assertEqual((rc, stderr), (0, ""))
            payload = json.loads(stdout)
            self.assertIn(
                "Update canonical source first: .github/agents/planner.agent.md",
                payload["change_checklist"],
            )

    def test_audit_reports_rendered_drift_and_ambiguous_canonical(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _authority_workspace(root)
            _write(
                root,
                ".gemini/agents/planner.md",
                "---\nname: planner\ndescription: Another source.\nweld:\n"
                "  authority: true\n---\n",
            )

            self.assertEqual(_run(["agents", "discover"], root)[0], 0)
            rc, stdout, stderr = _run(["agents", "audit", "--json"], root)

            self.assertEqual((rc, stderr), (0, ""))
            codes = {finding["code"] for finding in json.loads(stdout)["findings"]}
            self.assertIn("ambiguous_canonical", codes)
            self.assertIn("rendered_copy_drift", codes)

    def test_inline_renders_missing_target_becomes_audit_finding(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _write(
                root,
                ".github/agents/planner.agent.md",
                "---\nname: planner\ndescription: Plans changes.\nweld:\n"
                "  authority: true\n  renders: [missing/planner.md]\n---\n",
            )

            self.assertEqual(_run(["agents", "discover"], root)[0], 0)
            rc, stdout, stderr = _run(["agents", "audit", "--json"], root)

            self.assertEqual((rc, stderr), (0, ""))
            codes = {finding["code"] for finding in json.loads(stdout)["findings"]}
            self.assertIn("missing_render_target", codes)


def _authority_workspace(root: Path) -> None:
    _write(
        root,
        ".github/agents/planner.agent.md",
        "---\nname: planner\ndescription: Plans implementation changes.\n---\n",
    )
    _write(
        root,
        ".claude/agents/planner.md",
        "---\nname: planner\ndescription: Drafts implementation plans.\n---\n"
        "<!-- Generated by Weld -->\n",
    )
    _write(
        root,
        ".weld/agents.yaml",
        "agents:\n"
        "  planner:\n"
        "    canonical: .github/agents/planner.agent.md\n"
        "    renders:\n"
        "      - .claude/agents/planner.md\n",
    )


if __name__ == "__main__":
    unittest.main()
