"""Synthetic large-repo generator for benchmark scenarios.

Generates a deterministic on-disk Python tree that Weld discovery can run
against, plus optional polyrepo workspaces. The output is a tempdir-style
directory you point ``wd discover`` at; nothing is committed back into the
caller's repository.

Two layouts are supported:

* **single** -- one repository with ``--files`` files and a configurable
  number of imports per file.
* **polyrepo** -- a workspace root containing ``--children`` nested git
  repositories, each with ``--files`` files. Each child gets its own
  ``.weld/`` so federation runs the way it would for a real workspace.

The generator is intentionally minimal: it produces realistic-looking
Python modules (functions, imports, docstrings) but does not try to be
representative of any particular real codebase. Its purpose is to give
discovery a tree of known shape so timings can be reproduced.

Usage as a CLI::

    python -m weld.bench.synthetic_large_repo \\
        --layout single --files 1000 --output /tmp/synthetic-1k

    python -m weld.bench.synthetic_large_repo \\
        --layout polyrepo --children 5 --files 1000 \\
        --output /tmp/polyrepo-5x1k

The generator only writes files; it does not run discovery. Callers run
``wd discover`` (or ``wd workspace bootstrap`` for polyrepo) on the
output directory and time it themselves. See ``docs/performance.md``.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

# Module body template. Keep it small but include the shapes Weld
# discovery cares about: imports (edges), function defs (symbols),
# a docstring (markdown-ish), and a class.
_MODULE_TEMPLATE = '''"""Synthetic module {module_name}.

Generated by weld.bench.synthetic_large_repo for benchmark scenarios.
Not for human reading.
"""

from __future__ import annotations

{imports}


def helper_{idx}(value: int) -> int:
    """Return ``value`` doubled."""
    return value * 2


def process_{idx}(items: list[int]) -> list[int]:
    """Apply :func:`helper_{idx}` to each element."""
    return [helper_{idx}(x) for x in items]


class Worker{idx}:
    """Trivial worker class for benchmark scaffolding."""

    def __init__(self, label: str) -> None:
        self.label = label

    def run(self, items: list[int]) -> list[int]:
        """Delegate to :func:`process_{idx}`."""
        return process_{idx}(items)
'''


@dataclass(frozen=True)
class GenSpec:
    """Specification for a single repository to generate."""

    root: Path
    files: int
    imports_per_file: int = 2
    package_name: str = "synthrepo"


def _write_module(spec: GenSpec, idx: int, total: int) -> None:
    """Write ``module_<idx>.py`` under ``<root>/<package>/``."""
    pkg_dir = spec.root / spec.package_name
    # Distribute modules across subpackages of ~256 files to avoid one
    # giant directory (which is unrealistic and exercises a different
    # code path in some filesystems).
    bucket = idx // 256
    sub = pkg_dir / f"pkg_{bucket:04d}"
    sub.mkdir(parents=True, exist_ok=True)
    init_path = sub / "__init__.py"
    if not init_path.exists():
        init_path.write_text("", encoding="utf-8")

    # Deterministic intra-package imports so the call graph has shape.
    target_indices: list[int] = []
    for offset in range(1, spec.imports_per_file + 1):
        target_indices.append((idx + offset) % total)
    import_lines = "\n".join(
        f"from {spec.package_name}.pkg_{j // 256:04d}.module_{j} "
        f"import helper_{j}"
        for j in target_indices
        if j != idx
    )
    body = _MODULE_TEMPLATE.format(
        module_name=f"{spec.package_name}.module_{idx}",
        imports=import_lines or "# no imports in this synthetic module",
        idx=idx,
    )
    (sub / f"module_{idx}.py").write_text(body, encoding="utf-8")


def generate_single(spec: GenSpec) -> Path:
    """Generate a single synthetic Python repository at ``spec.root``.

    Creates ``spec.root`` if absent, writes ``spec.files`` Python modules
    under a ``pkg_<NNNN>`` bucket layout, and returns the root path. The
    caller is responsible for ``wd init`` / ``wd discover``.
    """
    spec.root.mkdir(parents=True, exist_ok=True)
    pkg_init = spec.root / spec.package_name / "__init__.py"
    pkg_init.parent.mkdir(parents=True, exist_ok=True)
    pkg_init.write_text("", encoding="utf-8")
    for idx in range(spec.files):
        _write_module(spec, idx, spec.files)
    return spec.root


def _git_init(path: Path) -> None:
    """Initialise a git repo at ``path`` and make a single commit.

    Needed for polyrepo federation: each child must be its own git
    repository with at least one commit so ``wd init`` recognises it.
    """
    subprocess.run(
        ["git", "init", "--quiet", "--initial-branch=main"],
        cwd=path,
        check=True,
    )
    # Local-only identity so this works in throwaway tempdirs without
    # touching the user's global git config.
    env = os.environ.copy()
    env.update(
        {
            "GIT_AUTHOR_NAME": "weld-bench",
            "GIT_AUTHOR_EMAIL": "weld-bench@example.invalid",
            "GIT_COMMITTER_NAME": "weld-bench",
            "GIT_COMMITTER_EMAIL": "weld-bench@example.invalid",
        }
    )
    subprocess.run(["git", "add", "-A"], cwd=path, check=True, env=env)
    subprocess.run(
        ["git", "commit", "--quiet", "-m", "initial"],
        cwd=path,
        check=True,
        env=env,
    )


def generate_polyrepo(
    root: Path,
    *,
    children: int,
    files_per_child: int,
    imports_per_file: int = 2,
) -> Path:
    """Generate a polyrepo workspace root with ``children`` git repos.

    Each child is a fully initialised git repo under ``<root>/repo_<NN>``
    so ``wd workspace bootstrap`` (which detects nested git repos) sees
    them as federation children. Returns the workspace root path.
    """
    root.mkdir(parents=True, exist_ok=True)
    # Initialise the workspace root as a git repo too -- ``wd init``
    # at the root is what produces ``.weld/workspaces.yaml``.
    if not (root / ".git").exists():
        subprocess.run(
            ["git", "init", "--quiet", "--initial-branch=main"],
            cwd=root,
            check=True,
        )
    for i in range(children):
        child_root = root / f"repo_{i:02d}"
        spec = GenSpec(
            root=child_root,
            files=files_per_child,
            imports_per_file=imports_per_file,
            package_name=f"repo_{i:02d}_pkg",
        )
        generate_single(spec)
        _git_init(child_root)
    return root


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m weld.bench.synthetic_large_repo",
        description=(
            "Generate a synthetic Python repository (or polyrepo "
            "workspace) for benchmarking weld discovery and queries."
        ),
    )
    p.add_argument(
        "--layout",
        choices=("single", "polyrepo"),
        default="single",
        help="Repository shape to generate (default: single).",
    )
    p.add_argument(
        "--files",
        type=int,
        default=1000,
        help=(
            "Total Python files for single layout, or files per child "
            "for polyrepo layout (default: 1000)."
        ),
    )
    p.add_argument(
        "--children",
        type=int,
        default=5,
        help="Number of child repos for polyrepo layout (default: 5).",
    )
    p.add_argument(
        "--imports-per-file",
        type=int,
        default=2,
        help="Intra-package import edges per module (default: 2).",
    )
    p.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output directory (will be created if absent).",
    )
    p.add_argument(
        "--clean",
        action="store_true",
        help=(
            "Remove --output before generating. Off by default to avoid "
            "accidental data loss."
        ),
    )
    return p


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Returns process exit code."""
    args = _build_parser().parse_args(argv)
    out: Path = args.output
    if args.clean and out.exists():
        shutil.rmtree(out)
    if args.layout == "single":
        generate_single(
            GenSpec(
                root=out,
                files=args.files,
                imports_per_file=args.imports_per_file,
            )
        )
        print(
            f"generated single repo with {args.files} files at {out}",
            file=sys.stderr,
        )
    else:
        generate_polyrepo(
            out,
            children=args.children,
            files_per_child=args.files,
            imports_per_file=args.imports_per_file,
        )
        print(
            f"generated polyrepo workspace ({args.children} children x "
            f"{args.files} files) at {out}",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
