#!/usr/bin/env bash
# Create a Weld monorepo demo workspace in a clean target directory.
#
# Usage:
#   scripts/create-monorepo-demo.sh <target-dir>
#
# Lays down a small TypeScript-flavored monorepo (apps/, packages/,
# libs/, services/), initializes a single git repo at the root with a
# seed commit, and writes a .weld/discover.yaml suitable for
# `wd discover`.
#
# After this script finishes you can run, from <target-dir>:
#
#   wd discover --output .weld/graph.json
#   wd build-index
#   wd find "Button"
#   wd query "orders-api"
#
# Linux/macOS, bash + standard tools, no exotic deps.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "${SCRIPT_DIR}/_demo_common.sh"

demo_require_tools
demo_require_git_identity

TARGET_DIR="$(demo_resolve_target "${1:-}")"

note "Creating monorepo demo in: ${TARGET_DIR}"

mkdir -p "${TARGET_DIR}/apps/web/src"
mkdir -p "${TARGET_DIR}/packages/ui/src"
mkdir -p "${TARGET_DIR}/packages/api/src"
mkdir -p "${TARGET_DIR}/libs/shared-types/src"
mkdir -p "${TARGET_DIR}/services/orders-api/src"
mkdir -p "${TARGET_DIR}/.weld"

# ---------------------------------------------------------------------------
# Root manifest + README
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/README.md" <<'EOF'
# Weld monorepo demo

A minimal TypeScript-flavored monorepo: web app, UI and API packages,
shared types library, and an orders backend service. Generated by
`scripts/create-monorepo-demo.sh`.

Quickstart:

```bash
wd discover --output .weld/graph.json
wd build-index
wd find "Button"
wd query "orders-api"
```
EOF

cat > "${TARGET_DIR}/package.json" <<'EOF'
{
  "name": "@acme/monorepo-demo",
  "private": true,
  "workspaces": [
    "apps/*",
    "packages/*",
    "libs/*",
    "services/*"
  ]
}
EOF

cat > "${TARGET_DIR}/.weld/discover.yaml" <<'EOF'
# Weld discovery configuration for the @acme monorepo demo.
sources:
  - glob: "packages/ui/src/**/*.{ts,tsx}"
    type: file
    strategy: typescript_exports
    id_prefix: ui
    package: "pkg:ui"

  - glob: "packages/api/src/**/*.ts"
    type: file
    strategy: typescript_exports
    id_prefix: api
    package: "pkg:api"

  - glob: "apps/web/src/**/*.{ts,tsx}"
    type: file
    strategy: typescript_exports
    id_prefix: web
    package: "pkg:web"

  - glob: "libs/shared-types/src/**/*.ts"
    type: file
    strategy: typescript_exports
    id_prefix: shared-types
    package: "lib:shared-types"

  - glob: "services/orders-api/src/**/*.ts"
    type: file
    strategy: typescript_exports
    id_prefix: orders-api
    package: "service:orders-api"

  - glob: "**/package.json"
    type: config
    strategy: manifest
EOF

# ---------------------------------------------------------------------------
# packages/ui
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/packages/ui/package.json" <<'EOF'
{ "name": "@acme/ui", "version": "0.1.0", "main": "src/index.ts" }
EOF

cat > "${TARGET_DIR}/packages/ui/src/index.ts" <<'EOF'
export { Button } from "./Button";
EOF

cat > "${TARGET_DIR}/packages/ui/src/Button.tsx" <<'EOF'
export interface ButtonProps {
  label: string;
  onClick?: () => void;
}

export function Button(props: ButtonProps) {
  return null as any;
}
EOF

# ---------------------------------------------------------------------------
# packages/api
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/packages/api/package.json" <<'EOF'
{ "name": "@acme/api", "version": "0.1.0", "main": "src/client.ts" }
EOF

cat > "${TARGET_DIR}/packages/api/src/client.ts" <<'EOF'
import type { Item, Order } from "@acme/shared-types";

export async function listOrders(): Promise<Order[]> {
  return [];
}

export async function getItem(id: string): Promise<Item | null> {
  return null;
}
EOF

# ---------------------------------------------------------------------------
# apps/web
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/apps/web/package.json" <<'EOF'
{ "name": "@acme/web", "version": "0.1.0", "main": "src/App.tsx" }
EOF

cat > "${TARGET_DIR}/apps/web/src/App.tsx" <<'EOF'
import { Button } from "@acme/ui";
import { listOrders } from "@acme/api";

export function App() {
  void listOrders;
  void Button;
  return null as any;
}
EOF

# ---------------------------------------------------------------------------
# libs/shared-types
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/libs/shared-types/package.json" <<'EOF'
{ "name": "@acme/shared-types", "version": "0.1.0", "main": "src/index.ts" }
EOF

cat > "${TARGET_DIR}/libs/shared-types/src/index.ts" <<'EOF'
export interface Item {
  id: string;
  name: string;
}

export interface Order {
  id: string;
  items: Item[];
}

export interface ApiError {
  code: string;
  message: string;
}
EOF

# ---------------------------------------------------------------------------
# services/orders-api
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/services/orders-api/package.json" <<'EOF'
{ "name": "@acme/orders-api", "version": "0.1.0", "main": "src/server.ts" }
EOF

cat > "${TARGET_DIR}/services/orders-api/src/server.ts" <<'EOF'
import type { Order } from "@acme/shared-types";

export function createOrder(order: Order): Order {
  return order;
}

export function getOrder(id: string): Order | null {
  return null;
}

export function listOrders(): Order[] {
  return [];
}
EOF

# ---------------------------------------------------------------------------
# Initialize a single git repo at the root with a seed commit.
# Unlike polyrepo, monorepos use one git repository for the whole tree.
# ---------------------------------------------------------------------------
demo_seed_repo "${TARGET_DIR}" "demo seed: monorepo"

note "Monorepo demo ready."
note ""
note "Next:"
note "  cd ${TARGET_DIR}"
note "  wd discover --output .weld/graph.json"
note "  wd build-index"
note "  wd find \"Button\""
note "  wd query \"orders-api\""
