#!/usr/bin/env bash
# Create a Weld polyrepo demo workspace in a clean target directory.
#
# Usage:
#   scripts/create-polyrepo-demo.sh <target-dir>
#
# Lays down a three-child polyrepo (services-api, services-auth,
# libs-shared-models), initializes each child as its own git repo with
# a seed commit, writes per-child and root .weld configs, and leaves
# the workspace ready for `wd discover` and `wd workspace status`.
#
# After this script finishes you can run, from <target-dir>:
#
#   for child in services/api services/auth libs/shared-models; do
#     (cd "$child" && wd discover --output .weld/graph.json)
#   done
#   wd discover --output .weld/graph.json
#   wd workspace status
#   wd query "tokens"
#
# Linux/macOS, bash + standard tools, no exotic deps.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "${SCRIPT_DIR}/_demo_common.sh"

demo_require_tools
demo_require_git_identity

TARGET_DIR="$(demo_resolve_target "${1:-}")"

note "Creating polyrepo demo in: ${TARGET_DIR}"

# ---------------------------------------------------------------------------
# Layout: three children + workspace registry
# ---------------------------------------------------------------------------
mkdir -p "${TARGET_DIR}/services/api/src"
mkdir -p "${TARGET_DIR}/services/api/.weld"
mkdir -p "${TARGET_DIR}/services/auth/src/routers"
mkdir -p "${TARGET_DIR}/services/auth/.weld"
mkdir -p "${TARGET_DIR}/libs/shared-models/src/shared_models"
mkdir -p "${TARGET_DIR}/libs/shared-models/.weld"
mkdir -p "${TARGET_DIR}/.weld"

# ---------------------------------------------------------------------------
# Root README + workspaces.yaml
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/README.md" <<'EOF'
# Weld polyrepo demo

A three-child polyrepo: `services-api` calls `services-auth`'s
`POST /tokens` endpoint, and both depend on `libs-shared-models`.
Generated by `scripts/create-polyrepo-demo.sh`.

Quickstart:

```bash
for child in services/api services/auth libs/shared-models; do
  (cd "$child" && wd discover --output .weld/graph.json)
done
wd discover --output .weld/graph.json
wd workspace status
wd query "tokens"
```
EOF

cat > "${TARGET_DIR}/.weld/workspaces.yaml" <<'EOF'
version: 1
scan:
  max_depth: 3
  exclude_paths: [.worktrees, vendor]
children:
  - name: services-api
    path: services/api
    tags:
      category: services
  - name: services-auth
    path: services/auth
    tags:
      category: services
  - name: libs-shared-models
    path: libs/shared-models
    tags:
      category: libs
cross_repo_strategies: [service_graph]
EOF

cat > "${TARGET_DIR}/.weld/discover.yaml" <<'EOF'
sources:
  - glob: "README.md"
    type: doc
    strategy: markdown
    id_prefix: root
    doc_kind: guide
EOF

# ---------------------------------------------------------------------------
# services/api
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/services/api/.weld/discover.yaml" <<'EOF'
sources:
  - glob: "src/**/*.py"
    type: file
    strategy: python_module

  - glob: "src/**/*.py"
    type: file
    strategy: http_client
EOF

cat > "${TARGET_DIR}/services/api/src/__init__.py" <<'EOF'
"""api service package."""
EOF

cat > "${TARGET_DIR}/services/api/src/server.py" <<'EOF'
"""api service: calls services-auth for token issuance."""

from __future__ import annotations

import httpx
from fastapi import FastAPI

app = FastAPI(title="api")


@app.post("/login")
def login(username: str) -> dict:
    """Exchange a username for a token by calling the auth service."""
    response = httpx.post(
        "http://services-auth:8080/tokens",
        json={"subject": username},
        timeout=5.0,
    )
    response.raise_for_status()
    return response.json()
EOF

# ---------------------------------------------------------------------------
# services/auth
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/services/auth/.weld/discover.yaml" <<'EOF'
sources:
  - glob: "src/**/*.py"
    type: file
    strategy: python_module

  - glob: "src/routers/*.py"
    type: file
    strategy: fastapi
EOF

cat > "${TARGET_DIR}/services/auth/src/__init__.py" <<'EOF'
"""auth service package."""
EOF

cat > "${TARGET_DIR}/services/auth/src/app.py" <<'EOF'
"""auth service: FastAPI app wiring."""

from __future__ import annotations

from fastapi import FastAPI

from .routers.tokens import router as tokens_router

app = FastAPI(title="auth")
app.include_router(tokens_router)
EOF

cat > "${TARGET_DIR}/services/auth/src/routers/__init__.py" <<'EOF'
"""auth routers."""
EOF

cat > "${TARGET_DIR}/services/auth/src/routers/tokens.py" <<'EOF'
"""POST /tokens -- the cross-repo match target for services-api."""

from __future__ import annotations

from fastapi import APIRouter

router = APIRouter()


@router.post("/tokens")
def create_token(req: dict) -> dict:
    """Return a fresh token for the given subject."""
    subject = req.get("subject", "anon")
    return {"subject": subject, "value": f"tok-{subject}"}
EOF

# ---------------------------------------------------------------------------
# libs/shared-models
# ---------------------------------------------------------------------------
cat > "${TARGET_DIR}/libs/shared-models/.weld/discover.yaml" <<'EOF'
sources:
  - glob: "src/**/*.py"
    type: file
    strategy: python_module

  - glob: "src/**/*.py"
    type: file
    strategy: pydantic
EOF

cat > "${TARGET_DIR}/libs/shared-models/src/shared_models/__init__.py" <<'EOF'
"""Shared domain models for the polyrepo demo."""

from .models import Token, TokenRequest

__all__ = ["Token", "TokenRequest"]
EOF

cat > "${TARGET_DIR}/libs/shared-models/src/shared_models/models.py" <<'EOF'
"""Shared domain models used by both services in the polyrepo demo."""

from __future__ import annotations

from pydantic import BaseModel


class TokenRequest(BaseModel):
    """Input payload for POST /tokens."""

    subject: str


class Token(BaseModel):
    """A minimal bearer token returned by the auth service."""

    subject: str
    value: str
EOF

# ---------------------------------------------------------------------------
# Initialize each child as its own git repo with a seed commit.
# Federation requires a real .git/ in every child; that is the friction
# this script removes.
# ---------------------------------------------------------------------------
for child in services/api services/auth libs/shared-models; do
  demo_seed_repo "${TARGET_DIR}/${child}" "demo seed: ${child}"
done

note "Polyrepo demo ready."
note ""
note "Next:"
note "  cd ${TARGET_DIR}"
note "  for child in services/api services/auth libs/shared-models; do"
note "    (cd \"\$child\" && wd discover --output .weld/graph.json)"
note "  done"
note "  wd discover --output .weld/graph.json"
note "  wd workspace status"
note "  wd query \"tokens\""
