"""The comment header ``wd init`` writes atop every generated discover.yaml.

Split out of ``weld/init.py`` purely to keep that module under its line
cap -- this is a static documentation string, not logic, so lifting it
into its own module is a mechanical split with zero behavior change
(mirrors why ``weld/_init_csharp.py`` / ``weld/_init_ros2.py`` /
``weld/_init_go.py`` live outside ``init.py`` too, though those also
carry real detection logic and this does not).
"""

from __future__ import annotations

YAML_HEADER = """\
# .weld/discover.yaml — Auto-generated by `wd init`.
#
# Sources are organized by artifact class so the connected structure covers the
# whole codebase — not just application code.  Uncomment or add entries for
# any class that applies to this repository.
#
# Artifact classes:
#   code        — application source, domain models, routes, contracts
#   docs        — markdown documentation, ADRs, guides
#   policy      — project policies, agent definitions, runbooks
#   infra       — Dockerfiles, compose files, deploy manifests
#   build       — build configs, CI workflows, Bazel/Make/npm targets
#   tests       — test suites, fixtures, test utilities
#   operations  — scripts, tools, operational runbooks
#
# Available strategies:
#   sqlalchemy      — AST: SQLAlchemy Base subclasses, FKs, columns, StrEnum
#   fastapi         — AST: APIRouter + @router decorators
#   flask           — AST: Flask/Blueprint + @app.route/@bp.route decorators
#   gin             — Regex: gin route registration (r.GET/POST/Any/Handle)
#   axum            — Regex: axum route registration (.route("/p", get(h)))
#   express         — Regex: express route registration (app.get / .route(..).get)
#   next            — Files: Next.js app-router route.* handler exports + page.*
#   pydantic        — AST: BaseModel subclasses, fields, docstrings
#   worker_stage    — AST: __init__.py __all__ exports in stage subdirs
#   dockerfile      — Line parse: FROM base image
#   compose         — Line parse: services block
#   frontmatter_md  — YAML frontmatter: name, description, model
#   firstline_md    — First content line as description
#   tool_script     — Shebang detection for lang classification
#   yaml_meta       — Line parse: name + on triggers from YAML
#   markdown        — Markdown doc node from .md file
#   config_file     — Static config file node
#   python_module     — AST: top-level classes and functions
#   python_callgraph  — AST: function-level symbols + calls edges (ADR 0004)
#   tree_sitter       — Tree-sitter AST: exports, types, imports (Go, Rust, TS, JS, C#, Java, C/C++)
#   grpc_proto        — AST: .proto service/rpc/message/enum extraction
#   grpc_bindings     — AST: Python gRPC server/client bindings -> rpc edges
#   events            — Async channels (Kafka/Celery/Redis; compose env + py call sites)
#   events_bindings   — AST: Python channel producer/consumer/payload linkage
#   runtime_contract  — runtime-contract.md healthchecks + boundary linkage
#   csharp_solution        — XML: .sln contains -> .csproj
#   csharp_project         — XML: .csproj ProjectReference, Directory.Build.*
#   csharp_msbuild_targets — XML: <Target> BeforeTargets/AfterTargets ordering
#   csharp_test_framework  — Attribute parse: xUnit / NUnit / MSTest markers
#   csharp_aspnet_routes   — Attribute parse: ASP.NET Core controllers + routes
#   csharp_efcore          — Attribute parse: DbContext / DbSet entities
#   cpp_buildsystem_detector — Build-system root probe (CMakeLists, BUILD, meson)
"""
