"""Authority metadata helpers for static Agent Graph discovery."""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from weld._yaml import parse_yaml
from weld.agent_graph_metadata_utils import jsonable

SIDECAR_PATH = ".weld/agents.yaml"

_GENERATED_MARKERS = (
    "generated by weld",
    "weld:generated",
    "@generated by weld",
)


@dataclass(frozen=True)
class AuthorityConfig:
    """Authority metadata loaded from optional sidecar config."""

    diagnostics: tuple[dict[str, Any], ...] = ()
    props_by_path: dict[str, dict[str, Any]] = field(default_factory=dict)
    sources: tuple[str, ...] = ()


def frontmatter_authority_props(frontmatter: dict[str, Any]) -> dict[str, Any]:
    """Extract normalized authority props from frontmatter ``weld`` metadata."""
    weld = frontmatter.get("weld")
    if not isinstance(weld, dict):
        return {}
    props: dict[str, Any] = {}
    authority = _authority_value(weld.get("authority"))
    if authority:
        props["authority"] = authority
    renders = _renders(weld.get("renders"))
    if renders:
        props["renders"] = renders
    render_paths = _render_paths(weld.get("renders"))
    if render_paths:
        props["render_paths"] = render_paths
    return props


def generated_marker_props(text: str) -> dict[str, Any]:
    """Return generated-copy props when a static file carries a Weld marker."""
    lowered = text[:2000].casefold()
    if any(marker in lowered for marker in _GENERATED_MARKERS):
        return {"generated": True}
    return {}


def load_authority_config(root: Path) -> AuthorityConfig:
    """Load optional sidecar authority metadata from ``.weld/agents.yaml``."""
    sidecar = root / SIDECAR_PATH
    if not sidecar.is_file():
        return AuthorityConfig()
    try:
        parsed = parse_yaml(sidecar.read_text(encoding="utf-8"))
    except UnicodeDecodeError as exc:
        return AuthorityConfig(
            diagnostics=(_diagnostic(
                "agent_graph_unreadable_authority_config",
                f"Could not read Agent Graph authority config as UTF-8: {exc}",
            ),),
            sources=(SIDECAR_PATH,),
        )
    if not isinstance(parsed, dict):
        return AuthorityConfig(
            diagnostics=(_diagnostic(
                "agent_graph_invalid_authority_config",
                "Agent Graph authority config must be a mapping.",
            ),),
            sources=(SIDECAR_PATH,),
        )
    return AuthorityConfig(
        diagnostics=tuple(),
        props_by_path=_sidecar_props(parsed),
        sources=(SIDECAR_PATH,),
    )


def apply_authority_config(
    nodes: dict[str, dict],
    edges: list[dict],
    config: AuthorityConfig,
    *,
    source_strategy: str,
) -> list[dict[str, Any]]:
    """Annotate graph nodes with authority config and add render edges."""
    diagnostics: list[dict[str, Any]] = list(config.diagnostics)
    path_to_id = _path_to_id(nodes)
    for path, props in sorted(config.props_by_path.items()):
        node_id = path_to_id.get(path)
        if node_id is None:
            diagnostics.append(_diagnostic(
                "agent_graph_authority_target_missing",
                f"Authority config references undiscovered asset: {path}",
                reference=path,
            ))
            continue
        node_props = nodes[node_id].setdefault("props", {})
        node_props.update(copy.deepcopy(props))

    diagnostics.extend(_add_render_edges(nodes, edges, source_strategy=source_strategy))
    return diagnostics


def authority_sources(config: AuthorityConfig) -> list[str]:
    return list(config.sources)


def _sidecar_props(payload: dict[str, Any]) -> dict[str, dict[str, Any]]:
    props_by_path: dict[str, dict[str, Any]] = {}
    agents = payload.get("agents")
    if not isinstance(agents, dict):
        return props_by_path
    for name, config in sorted(agents.items(), key=lambda item: str(item[0])):
        if not isinstance(config, dict):
            continue
        canonical = _clean_path(config.get("canonical"))
        renders = _render_paths(config.get("renders"))
        if canonical:
            canonical_props = props_by_path.setdefault(canonical, {})
            canonical_props["authority"] = "canonical"
            canonical_props["authority_name"] = str(name)
            if renders:
                canonical_props["render_paths"] = renders
                canonical_props["renders"] = _renders(config.get("renders"))
        for render_path in renders:
            render_props = props_by_path.setdefault(render_path, {})
            render_props.setdefault("authority", "derived")
            render_props["generated_from"] = canonical
            render_props["authority_name"] = str(name)
    return props_by_path


def _add_render_edges(
    nodes: dict[str, dict],
    edges: list[dict],
    *,
    source_strategy: str,
) -> list[dict[str, Any]]:
    diagnostics: list[dict[str, Any]] = []
    seen = {
        (edge.get("from"), edge.get("to"), edge.get("type"), _edge_raw(edge))
        for edge in edges
    }
    path_to_id = _path_to_id(nodes)
    for canonical_id, node in sorted(nodes.items()):
        props = node.get("props") if isinstance(node.get("props"), dict) else {}
        canonical_path = str(props.get("file") or "")
        for render_path in props.get("render_paths") or []:
            render_id = path_to_id.get(_clean_path(render_path))
            if render_id is None:
                diagnostics.append(_diagnostic(
                    "agent_graph_missing_render_target",
                    f"Rendered copy does not exist: {render_path}",
                    source_node=canonical_id,
                    path=canonical_path,
                    reference=str(render_path),
                ))
                continue
            _add_edge(edges, seen, render_id, canonical_id, "generated_from", {
                "source_strategy": source_strategy,
                "confidence": "definite",
                "provenance": {
                    "file": canonical_path,
                    "line": 1,
                    "raw": str(render_path),
                    "target": canonical_path,
                    "target_type": "canonical",
                },
            })
    edges.sort(key=lambda edge: (
        edge["from"],
        edge["to"],
        edge["type"],
        _edge_raw(edge),
    ))
    return diagnostics


def _add_edge(
    edges: list[dict],
    seen: set[tuple[Any, Any, Any, str]],
    from_id: str,
    to_id: str,
    edge_type: str,
    props: dict[str, Any],
) -> None:
    key = (from_id, to_id, edge_type, _edge_raw({"props": props}))
    if key in seen:
        return
    seen.add(key)
    edges.append({"from": from_id, "to": to_id, "type": edge_type, "props": props})


def _path_to_id(nodes: dict[str, dict]) -> dict[str, str]:
    result: dict[str, str] = {}
    for node_id, node in nodes.items():
        props = node.get("props") if isinstance(node.get("props"), dict) else {}
        path = _clean_path(props.get("file"))
        if path:
            result[path] = node_id
    return result


def _authority_value(value: Any) -> str | None:
    if value is True:
        return "canonical"
    if value is False or value is None:
        return None
    text = str(value).strip().casefold()
    aliases = {"true": "canonical", "source": "canonical", "rendered": "derived"}
    return aliases.get(text, text)


def _renders(value: Any) -> list[Any]:
    if value is None:
        return []
    values = value if isinstance(value, list) else [value]
    return [jsonable(item) for item in values]


def _render_paths(value: Any) -> list[str]:
    paths: list[str] = []
    values = value if isinstance(value, list) else [value]
    for item in values:
        path = None
        if isinstance(item, dict):
            for key in ("path", "file", "target", "render"):
                if key in item:
                    path = item[key]
                    break
        else:
            path = item
        cleaned = _clean_path(path)
        if cleaned:
            paths.append(cleaned)
    return sorted(dict.fromkeys(paths))


def _clean_path(value: Any) -> str:
    if not isinstance(value, str):
        return ""
    cleaned = value.strip()
    return cleaned[2:] if cleaned.startswith("./") else cleaned


def _edge_raw(edge: dict[str, Any]) -> str:
    props = edge.get("props") if isinstance(edge.get("props"), dict) else {}
    provenance = props.get("provenance") if isinstance(props.get("provenance"), dict) else {}
    return str(provenance.get("raw", ""))


def _diagnostic(
    code: str,
    message: str,
    *,
    path: str = SIDECAR_PATH,
    reference: str | None = None,
    source_node: str | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "code": code,
        "message": message,
        "path": path,
        "severity": "warning",
    }
    if reference is not None:
        result["reference"] = reference
    if source_node is not None:
        result["source_node"] = source_node
    return result
