#!/usr/bin/env python3
"""Bootstrap a .weld/discover.yaml by scanning the project."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from weld._gitignore_writer import write_weld_gitignore
from weld._init_classify import classify_files
from weld._init_ros2 import ros2_source_entries
from weld.init_workspace import init_workspace as _init_workspace
from weld.init_detect import (
    detect_all_from_classified,
    detect_frameworks,
    detect_languages,
    detect_ros2,
    scan_files,
)

_YAML_HEADER = """\
# .weld/discover.yaml — Auto-generated by `wd init`.
#
# Sources are organized by artifact class so the connected structure covers the
# whole codebase — not just application code.  Uncomment or add entries for
# any class that applies to this repository.
#
# Artifact classes:
#   code        — application source, domain models, routes, contracts
#   docs        — markdown documentation, ADRs, guides
#   policy      — project policies, agent definitions, runbooks
#   infra       — Dockerfiles, compose files, deploy manifests
#   build       — build configs, CI workflows, Bazel/Make/npm targets
#   tests       — test suites, fixtures, test utilities
#   operations  — scripts, tools, operational runbooks
#
# Available strategies:
#   sqlalchemy      — AST: SQLAlchemy Base subclasses, FKs, columns, StrEnum
#   fastapi         — AST: APIRouter + @router decorators
#   pydantic        — AST: BaseModel subclasses, fields, docstrings
#   worker_stage    — AST: __init__.py __all__ exports in stage subdirs
#   dockerfile      — Line parse: FROM base image
#   compose         — Line parse: services block
#   frontmatter_md  — YAML frontmatter: name, description, model
#   firstline_md    — First content line as description
#   tool_script     — Shebang detection for lang classification
#   yaml_meta       — Line parse: name + on triggers from YAML
#   markdown        — Markdown doc node from .md file
#   config_file     — Static config file node
#   python_module     — AST: top-level classes and functions
#   python_callgraph  — AST: function-level symbols + calls edges (ADR 0004)
#   tree_sitter       — Tree-sitter AST: exports, types, imports (Go, Rust, TS, C#)
"""
# Tree-sitter-backed languages: name → tuple of file extensions.
# A language may map to multiple extensions (C++ covers .cpp/.cc/.h/...).
# Languages in ``_TREE_SITTER_EMIT_CALLS`` also emit function-level call
# graph nodes via the per-source ``emit_calls`` flag.
_TREE_SITTER_LANGUAGES: dict[str, tuple[str, ...]] = {
    "csharp": (".cs",),
    "go": (".go",),
    "rust": (".rs",),
    "typescript": (".ts",),
    "cpp": (".c", ".cc", ".cpp", ".cxx",
            ".h", ".hpp", ".hh", ".hxx", ".ipp", ".tpp"),
}
_TREE_SITTER_EMIT_CALLS: frozenset[str] = frozenset({"cpp"})

def _source_entry(
    glob: str, node_type: str, strategy: str,
    *, comment: str = "", extra: dict[str, str] | None = None,
) -> str:
    """Generate a single source entry as YAML text."""
    lines: list[str] = []
    if comment:
        lines.append(f"\n  # --- {comment} ---")
    lines.append(f'  - glob: "{glob}"')
    lines.append(f"    type: {node_type}")
    lines.append(f"    strategy: {strategy}")
    if extra:
        for k, v in extra.items():
            lines.append(f"    {k}: {v}")
    return "\n".join(lines)

def _files_entry(
    file_list: list[str], node_type: str, strategy: str,
    *, comment: str = "",
) -> str:
    """Generate a source entry using files: instead of glob:."""
    lines: list[str] = []
    if comment:
        lines.append(f"\n  # --- {comment} ---")
    inner = ", ".join(f'"{f}"' for f in file_list)
    lines.append(f"  - files: [{inner}]")
    lines.append(f"    type: {node_type}")
    lines.append(f"    strategy: {strategy}")
    return "\n".join(lines)

def _find_matching_glob(globs: list[str], keywords: tuple[str, ...]) -> str | None:
    """Find the first glob pattern that contains any of the keywords."""
    for g in globs:
        if any(k in g.lower() for k in keywords):
            return g
    return None

def _add_framework_sources(
    sources: list[str],
    framework_names: set[str],
    python_globs: list[str],
) -> None:
    """Append framework-specific source entries."""
    if "SQLAlchemy" in framework_names:
        matched = _find_matching_glob(
            python_globs, ("domain", "model", "entities", "libs"),
        )
        sources.append(_source_entry(
            matched or python_globs[0] if python_globs else "**/*.py",
            "entity", "sqlalchemy",
            comment="SQLAlchemy domain models" if matched
            else "SQLAlchemy models (adjust glob to match your model directory)",
        ))

    if "FastAPI" in framework_names:
        matched = _find_matching_glob(
            python_globs, ("router", "route", "api", "services"),
        )
        sources.append(_source_entry(
            matched or python_globs[0] if python_globs else "**/*.py",
            "route", "fastapi",
            comment="FastAPI routes" if matched
            else "FastAPI routes (adjust glob to match your router directory)",
        ))

    if "Pydantic" in framework_names:
        matched = _find_matching_glob(
            python_globs, ("contract", "schema", "dto", "libs"),
        )
        if matched:
            sources.append(_source_entry(
                matched, "contract", "pydantic",
                comment="Pydantic contracts/schemas",
            ))

def _section_header(label: str) -> str:
    """Return a YAML comment that marks an artifact-class section."""
    return f"\n  # ===== {label} ====="

def _make_stub(glob: str, node_type: str, strategy: str) -> list[str]:
    """Build commented-out YAML lines for a stub entry."""
    return [f'  # - glob: "{glob}"', f"  #   type: {node_type}", f"  #   strategy: {strategy}"]

# Artifact classes in display order.  Each tuple:
#   (class_name, stub_glob, stub_node_type, stub_strategy)
_ARTIFACT_CLASSES: list[tuple[str, str, str, str]] = [
    ("code",       "src/**/*.py",       "file",   "python_module"),
    ("docs",       "docs/**/*.md",      "doc",    "markdown"),
    ("policy",     "policies/**/*.md",  "doc",    "markdown"),
    ("infra",      "deploy/**/*.yaml",  "config", "config_file"),
    ("build",      "**/*.bazel",        "config", "config_file"),
    ("tests",      "tests/**/*.py",     "file",   "python_module"),
    ("operations", "tools/*.sh",        "tool",   "tool_script"),
]

def generate_yaml(
    languages: dict[str, int],
    frameworks: list[tuple[str, str, str]],
    dockerfiles: list[str], compose_files: list[str], ci_files: list[str],
    claude_agents: list[str], claude_commands: list[str],
    doc_dirs: list[str], python_globs: list[str], root_configs: list[str],
    ros2_pkg_roots: list[str] | None = None,
) -> str:
    """Generate the discover.yaml content using template strings.

    Sources are grouped into artifact-class sections so the starter
    config leads maintainers toward whole-codebase onboarding instead
    of code-only discovery.
    """
    # Buckets keyed by artifact class.  Order follows _ARTIFACT_CLASSES.
    buckets: dict[str, list[str]] = {cls: [] for cls, _, _, _ in _ARTIFACT_CLASSES}
    framework_names = {fw for fw, _, _ in frameworks}

    # --- code ---
    _add_framework_sources(buckets["code"], framework_names, python_globs)

    if "python" in languages:
        added: set[str] = set()
        for g in python_globs:
            if g not in added and not any(g in s for s in buckets["code"]):
                # Heuristic: test directories go into the tests bucket.
                if "test" in g.lower():
                    buckets["tests"].append(_source_entry(
                        g, "file", "python_module",
                        comment=f"Python tests in {g.split('/')[0]}",
                    ))
                else:
                    buckets["code"].append(_source_entry(
                        g, "file", "python_module",
                        comment=f"Python modules in {g.split('/')[0]}",
                    ))
                    # Pair every non-test python source with a call graph
                    # extractor entry (ADR 0004). The new entry uses the
                    # same glob but emits ``symbol`` nodes and ``calls``
                    # edges instead of file-level metadata.
                    buckets["code"].append(_source_entry(
                        g, "symbol", "python_callgraph",
                        comment=f"Python call graph in {g.split('/')[0]}",
                    ))
                added.add(g)

    # --- tree-sitter languages (Go, Rust, TypeScript, C/C++) ---
    for lang, exts in _TREE_SITTER_LANGUAGES.items():
        if lang not in languages:
            continue
        extras: dict[str, str] = {"language": lang}
        if lang in _TREE_SITTER_EMIT_CALLS:
            extras["emit_calls"] = "true"
        label = "C#" if lang == "csharp" else lang.capitalize()
        for ext in exts:
            buckets["code"].append(_source_entry(
                f"**/*{ext}", "file", "tree_sitter",
                comment=f"{label} sources ({ext})",
                extra=extras,
            ))
    # --- ROS2 (; helpers in weld/_init_ros2.py) ---
    if ros2_pkg_roots:
        buckets["code"].extend(ros2_source_entries(ros2_pkg_roots))

    # --- docs ---
    for doc_dir in doc_dirs:
        buckets["docs"].append(_source_entry(
            f"{doc_dir}/*.md", "doc", "markdown",
            comment=f"Documentation ({doc_dir})",
            extra={"id_prefix": f"doc:{doc_dir}"},
        ))

    # --- policy ---
    if claude_agents:
        buckets["policy"].append(_source_entry(
            ".claude/agents/*.md", "agent", "frontmatter_md",
            comment="Claude agents",
        ))
    if claude_commands:
        buckets["policy"].append(_source_entry(
            ".claude/commands/*.md", "command", "firstline_md",
            comment="Claude commands",
        ))

    # --- infra ---
    # dockerfile and compose strategies require ``glob``; a literal file name
    # is itself a valid single-file glob pattern. Emitting ``files`` here
    # would crash discovery with KeyError: 'glob'.
    for df in dockerfiles:
        buckets["infra"].append(_source_entry(
            df, "dockerfile", "dockerfile", comment="Dockerfiles",
        ))

    for cf in compose_files:
        buckets["infra"].append(_source_entry(
            cf, "compose", "compose", comment="Docker Compose",
        ))

    # --- build ---
    if ci_files:
        buckets["build"].append(_source_entry(
            ".github/workflows/*.yml", "workflow", "yaml_meta",
            comment="CI workflows",
        ))

    if root_configs:
        buckets["build"].append(_files_entry(
            root_configs, "config", "config_file",
            comment="Root configuration files",
        ))

    # --- Assemble sections ---
    sections: list[str] = []
    for cls, stub_glob, stub_type, stub_strat in _ARTIFACT_CLASSES:
        entries = buckets[cls]
        if entries:
            sections.append(_section_header(cls))
            sections.extend(entries)
        else:
            # Emit the stub so maintainers see the artifact class exists.
            sections.append(_section_header(cls + " (uncomment to enable)"))
            sections.extend(_make_stub(stub_glob, stub_type, stub_strat))

    block = "\n".join(sections) if sections else "  # No sources detected"
    return f"{_YAML_HEADER}\nsources:\n{block}\n"

# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def init(root: Path, output: Path, *, force: bool = False) -> bool:
    """Run project detection and generate discover.yaml.

    Returns True on success, False if file exists and force is not set.
    """
    if output.exists() and not force:
        print(f"discover.yaml already exists at {output}", file=sys.stderr)
        print("Use --force to overwrite.", file=sys.stderr)
        return False

    print("Scanning for files...", file=sys.stderr)
    files = scan_files(root)
    print(f"Found {len(files)} files total", file=sys.stderr)

    print("Scanning for languages...", file=sys.stderr)
    languages = detect_languages(files)
    for lang, count in languages.items():
        print(f"  Found {count} {lang.capitalize()} files", file=sys.stderr)

    print("Detecting frameworks...", file=sys.stderr)
    frameworks = detect_frameworks(root, files)
    for fw, _strategy, path in frameworks:
        print(f"  Detected {fw} in {path}", file=sys.stderr)

    # Single classifier pass over the file list. Every path-shape
    # detector reads the precomputed records instead of re-walking
    # ``files`` (ADR 0027).
    classified = classify_files(root, files)
    detected = detect_all_from_classified(classified)
    structure = detected["structure"]
    dockerfiles = detected["dockerfiles"]
    compose_files = detected["compose_files"]
    ci_files = detected["ci_files"]
    claude_agents = detected["claude_agents"]
    claude_commands = detected["claude_commands"]
    doc_dirs = detected["doc_dirs"]
    python_globs = detected["python_globs"] if "python" in languages else []
    root_configs = detected["root_configs"]
    ros2_pkg_roots = detect_ros2(root, files)

    print("Detecting project structure...", file=sys.stderr)
    print(f"  Structure: {structure}", file=sys.stderr)
    print("Scanning for Dockerfiles...", file=sys.stderr)
    for df in dockerfiles:
        print(f"  Found {df}", file=sys.stderr)
    if not dockerfiles:
        print("  No Dockerfiles found", file=sys.stderr)
    for cf in compose_files:
        print(f"  Found {cf}", file=sys.stderr)
    print("Scanning for CI configurations...", file=sys.stderr)
    for cf in ci_files:
        print(f"  Found .github/workflows/{cf}", file=sys.stderr)
    if not ci_files:
        print("  No CI workflows found", file=sys.stderr)
    print("Scanning for Claude definitions...", file=sys.stderr)
    if claude_agents:
        print(f"  Found {len(claude_agents)} agent definitions", file=sys.stderr)
    if claude_commands:
        print(f"  Found {len(claude_commands)} command definitions", file=sys.stderr)

    print("Generating discover.yaml...", file=sys.stderr)
    yaml_text = generate_yaml(
        languages=languages, frameworks=frameworks,
        dockerfiles=dockerfiles, compose_files=compose_files,
        ci_files=ci_files, claude_agents=claude_agents,
        claude_commands=claude_commands, doc_dirs=doc_dirs,
        python_globs=python_globs, root_configs=root_configs,
        ros2_pkg_roots=ros2_pkg_roots,
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(yaml_text, encoding="utf-8")
    print(f"Wrote {output}", file=sys.stderr)
    return True

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="wd init",
        description="Bootstrap a .weld/discover.yaml by scanning the project",
    )
    parser.add_argument(
        "root", nargs="?", default=".",
        help="Project root directory (default: current directory)",
    )
    parser.add_argument(
        "--output", "-o", default=None,
        help="Output path (default: <root>/.weld/discover.yaml)",
    )
    parser.add_argument(
        "--force", "-f", action="store_true",
        help="Overwrite existing discover.yaml / workspaces.yaml",
    )
    parser.add_argument(
        "--max-depth", type=int, default=4,
        help="Max depth when scanning for nested git repos (default: 4)",
    )
    parser.add_argument(
        "--ignore-all", action="store_true",
        help="Write a fully-ignoring .weld/.gitignore (every weld file ignored)",
    )
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    output = Path(args.output) if args.output else root / ".weld" / "discover.yaml"

    success = init(root, output, force=args.force)
    workspaces_out = root / ".weld" / "workspaces.yaml"
    if _init_workspace(
        root, workspaces_out, force=args.force, max_depth=args.max_depth,
    ):
        print(f"Wrote {workspaces_out}", file=sys.stderr)
    write_weld_gitignore(output.parent, ignore_all=args.ignore_all)
    if not success:
        sys.exit(1)

if __name__ == "__main__":
    main()
